Socrate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
# core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('upload_material/', views.upload_material, name='upload_material'),
    path('document/<int:pk>/', views.document_detail, name='document_detail'),
    path('video/<int:pk>/', views.video_detail, name='video_detail'),
    path('audio/<int:pk>/', views.audio_detail, name='audio_detail'),
    path('media/<path:path>/', views.serve_media, name='serve_media'),
    path('delete_material/<int:pk>/', views.delete_material, name='delete_material'),
    path('upload_voice_message/', views.upload_voice_message, name='upload_voice_message'),
]

core/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Material(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to='materials/')
    material_type = models.CharField(max_length=50)
    transcript = models.TextField(blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    entities = models.JSONField(blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_url(self):
        if self.material_type in ['pdf', 'word']:
            return reverse('core:document_detail', args=[str(self.id)])
        elif self.material_type == 'video':
            return reverse('core:video_detail', args=[str(self.id)])
        elif self.material_type == 'audio':
            return reverse('core:audio_detail', args=[str(self.id)])
        return '#'

    def get_file_url(self):
        return self.file.url


class ChatSession(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    material = models.ForeignKey('Material', on_delete=models.CASCADE)
    context = models.TextField(blank=True, null=True)
    summary = models.TextField(blank=True, null=True)  # Add this field to store conversation summary
    created_at = models.DateTimeField(auto_now_add=True)


class ChatMessage(models.Model):
    chat_session = models.ForeignKey(ChatSession, related_name='messages', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    message_type = models.CharField(max_length=10, default='text')
    voice_file = models.FileField(upload_to='voice_messages/', null=True, blank=True)

    def __str__(self):
        return self.content

core/views.py
import base64
import json

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseServerError, JsonResponse
from django.utils.http import http_date
from wsgiref.util import FileWrapper
from .models import Material, ChatSession
from .utils import process_material, summarize_text, extract_entities
import os

User = get_user_model()


@login_required
def home_page(request):
    materials = Material.objects.filter(user=request.user)

    for material in materials:
        material.url = material.get_url()
        material.file_url = material.get_file_url()
    return render(request, 'core/home_page.html', {'materials': materials})


def create_chat_session_and_get_context(request, material):
    context = f"Transcript: {material.transcript}\nSummary: {material.summary}\nEntities: {material.entities}"
    chat_session, created = ChatSession.objects.get_or_create(material=material, user=request.user,
                                                              defaults={'context': context})
    chat_messages = chat_session.messages.all()
    return {
        'material': material,
        'material_data': json.dumps({'file_url': material.get_file_url(), 'material_type': material.material_type}),
        'chat_messages': chat_messages,
        'chat_session': chat_session.pk
    }


@login_required
def document_detail(request, pk):
    material = get_object_or_404(Material, pk=pk, user=request.user)
    context = create_chat_session_and_get_context(request, material)
    return render(request, 'core/document.html', context)


@login_required
def video_detail(request, pk):
    material = get_object_or_404(Material, pk=pk)
    context = create_chat_session_and_get_context(request, material)
    return render(request, 'core/video.html', context)


@login_required
def audio_detail(request, pk):
    material = get_object_or_404(Material, pk=pk)
    context = create_chat_session_and_get_context(request, material)
    return render(request, 'core/audio.html', context)


@login_required
def delete_material(request, pk):
    if request.method == 'POST':
        material = get_object_or_404(Material, pk=pk, user=request.user)
        try:
            material.delete()
            return JsonResponse({'success': True})
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})


def serve_media(request, path):
    try:
        media_path = os.path.join('media', path)
        extension = os.path.splitext(media_path)[1].lower()

        video_extensions = ['.mp4', '.avi', '.mov']
        audio_extensions = ['.wav', '.mp3']

        if extension in video_extensions:
            content_type = 'video/mp4'
        elif extension in audio_extensions:
            content_type = 'audio/mpeg'
        else:
            return HttpResponseNotFound('<h1>File type not supported</h1>')

        file_size = os.path.getsize(media_path)
        file = open(media_path, 'rb')

        content_range = request.headers.get('Range', None)
        if content_range:
            content_range = content_range.strip().split('=')[-1]
            range_start, range_end = content_range.split('-')
            range_start = int(range_start)
            range_end = int(range_end) if range_end else file_size - 1
            length = range_end - range_start + 1
            file.seek(range_start)
            response = HttpResponse(
                FileWrapper(file, length),
                status=206,
                content_type=content_type,
            )
            response['Content-Length'] = str(length)
            response['Content-Range'] = f'bytes {range_start}-{range_end}/{file_size}'
        else:
            response = HttpResponse(
                FileWrapper(file),
                content_type=content_type,
            )
            response['Content-Length'] = str(file_size)
        response['Accept-Ranges'] = 'bytes'
        response['Last-Modified'] = http_date(os.path.getmtime(media_path))
        return response
    except FileNotFoundError:
        return HttpResponseNotFound('<h1>File not found</h1>')
    except Exception as e:
        return HttpResponseServerError(f'<h1>Server error: {e}</h1>')


@login_required
def upload_material(request):
    if request.method == 'POST':
        file_title = request.POST.get('file_title')
        uploaded_file = request.FILES.get('material')

        if uploaded_file:
            extension = os.path.splitext(uploaded_file.name)[1].lower()
            if extension in ['.pdf']:
                material_type = 'pdf'
            elif extension in ['.doc', '.docx']:
                material_type = 'word'
            elif extension in ['.mp4', '.avi', '.mov']:
                material_type = 'video'
            elif extension in ['.wav', '.mp3']:
                material_type = 'audio'
            else:
                material_type = 'unsupported'

            if material_type == 'unsupported':
                return JsonResponse({'success': False, 'error': 'Unsupported file type'})

            try:
                # Save material instance to make file accessible at material.file.path
                material = Material.objects.create(
                    user=request.user,
                    title=file_title,
                    file=uploaded_file,
                    material_type=material_type
                )

                file_path = material.file.path
                processed_text = process_material(material_type, file_path)

                if processed_text:
                    material.transcript = processed_text
                    material.summary = summarize_text(processed_text)
                    material.entities = extract_entities(processed_text)

                    # Convert summary and entities to strings if they are lists or non-string types
                    if isinstance(material.summary, list):
                        material.summary = " ".join(material.summary)  # Join list into a single string
                    elif not isinstance(material.summary, str):
                        material.summary = str(material.summary)  # Convert any other types to string

                    if isinstance(material.entities, list):
                        material.entities = " ".join(
                            [f"{ent[0]} ({ent[1]})" for ent in material.entities])  # Format entity list to string
                    elif not isinstance(material.entities, str):
                        material.entities = str(material.entities)  # Convert any other types to string

                    # Only save if transcript, summary, and entities are set and non-empty
                    if all([material.transcript, material.summary, material.entities]) and \
                            all([material.transcript.strip(), material.summary.strip(), material.entities.strip()]):
                        material.save()
                        return JsonResponse({'success': True, 'material_id': material.id})
                    else:
                        # Dispose of the material object if fields are empty
                        material.delete()
                        return JsonResponse(
                            {'success': False, 'error': 'Processing incomplete. Required fields are empty.'})

                else:
                    # Dispose of the material object if processing fails
                    material.delete()
                    return JsonResponse({'success': False, 'error': 'Error processing material text'})

            except Exception as e:
                return JsonResponse({'success': False, 'error': str(e)})
        else:
            return JsonResponse({'success': False, 'error': 'No file uploaded'})

    return render(request, 'core/home_page.html')


def upload_voice_message(request):
    if request.method == 'POST':
        chat_session_id = request.POST.get('chat_session_id')
        uploaded_file = request.FILES.get('voice_message')

        if uploaded_file and chat_session_id:
            try:
                fs = FileSystemStorage()
                filename = fs.save(uploaded_file.name, uploaded_file)
                file_path = fs.path(filename)

                with open(file_path, 'rb') as audio_file:
                    audio_base64 = base64.b64encode(audio_file.read()).decode('utf-8')

                return JsonResponse({'success': True, 'audio_base64': audio_base64})
            except Exception as e:
                return JsonResponse({'success': False, 'error': str(e)})
        else:
            return JsonResponse({'success': False, 'error': 'No file uploaded or chat_session_id not provided'})

    return JsonResponse({'success': False, 'error': 'Invalid request method'})

templates/core/audio.html
{% extends 'core/sub_base.html' %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/audio.css' %}">
{% endblock %}

{% block sub_content %}
    <div style="display: flex;flex-direction: column;align-items: center;justify-content: center;width: 100%;height: 100%">
        <div class="audio-container">
            <audio id="myAudio">
                <source src="{% url 'core:serve_media' path=material.file.name %}" type="audio/mp3">
                Your browser does not support the audio element.
            </audio>
            <div class="controls">
                <button class="control_buttons" id="playPauseBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30px" height="30px" viewBox="0 0 24 24">
                        <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.5"
                              d="M3 12v6.967c0 2.31 2.534 3.769 4.597 2.648l3.203-1.742M3 8V5.033c0-2.31 2.534-3.769 4.597-2.648l12.812 6.968a2.998 2.998 0 0 1 0 5.294l-6.406 3.484"/>
                    </svg>
                </button>
                <input type="range" id="seekBar" max="100" min="0" value="0" class="custom-range">
                <button class="control_buttons" id="muteBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 24 24">
                        <path fill="currentColor"
                              d="M12 3.75v16.5a.75.75 0 0 1-1.255.555L5.46 16H2.75A1.75 1.75 0 0 1 1 14.25v-4.5C1 8.784 1.784 8 2.75 8h2.71l5.285-4.805A.75.75 0 0 1 12 3.75M6.255 9.305a.75.75 0 0 1-.505.195h-3a.25.25 0 0 0-.25.25v4.5c0 .138.112.25.25.25h3c.187 0 .367.069.505.195l4.245 3.86V5.445ZM16.28 8.22a.75.75 0 1 0-1.06 1.06L17.94 12l-2.72 2.72a.75.75 0 1 0 1.06 1.06L19 13.06l2.72 2.72a.75.75 0 1 0 1.06-1.06L20.06 12l2.72-2.72a.75.75 0 0 0-1.06-1.06L19 10.94z"/>
                    </svg>
                </button>
                <button class="control_buttons" id="volumeBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30px" height="30px" viewBox="0 0 48 48">
                        <g fill="none" stroke="currentColor" stroke-width="4">
                            <path d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4S4 12.954 4 24s8.954 20 20 20Z"/>
                            <path stroke-linecap="round" d="M30 18v12m6-8v4m-18-8v12m-6-8v4m12-12v20"/>
                        </g>
                    </svg>
                </button>
                <div class="volume-slider">
                    <input type="range" id="volumeBar" value="1" min="0" max="1" step="0.1" class="custom-range">
                </div>
                <span class="time-display" id="currentTime">0:00</span> <span class="time-display">/</span> <span
                    class="time-display" id="duration">0:00</span>
            </div>
        </div>
    </div>
    <input type="hidden" id="chatSessionId" value="{{ chat_session }}">

{% endblock %}

{% block js %}
    <script src="{% static 'js/audio.js' %}"></script>
    <script src="{% static 'js/chat.js' %}"></script>
{% endblock %}

templates/core/document.html
{% extends 'core/sub_base.html' %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/document.css' %}">
{% endblock %}

{% block sub_content %}
    <div id="materialData" style="display:none;">{{ material_data|safe }}</div>
    <div class="main_container">
        <div style="display: flex;flex-direction: row;align-items: center;justify-content: center">
            <div id="zoomControls">
                <button id="zoomOutBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M19 11H5v2h14z"/>
                    </svg>
                </button>
                <button id="zoomInBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6z"/>
                    </svg>
                </button>
            </div>
            <div id="pageControls">
                <button id="prevPageBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                        <g fill="none" fill-rule="evenodd">
                            <path d="M24 0v24H0V0zM12.593 23.258l-.011.002l-.071.035l-.02.004l-.014-.004l-.071-.035q-.016-.005-.024.005l-.004.01l-.017.428l.005.02l.01.013l.104.074l.015.004l.012-.004l.104-.074l.012-.016l.004-.017l-.017-.427q-.004-.016-.017-.018m.265-.113l-.013.002l-.185.093l-.01.01l-.003.011l.018.43l.005.012l.008.007l.201.093q.019.005.029-.008l.004-.014l-.034-.614q-.005-.019-.02-.022m-.715.002a.02.02 0 0 0-.027.006l-.006.014l-.034.614q.001.018.017.024l.015-.002l.201-.093l.01-.008l.004-.011l.017-.43l-.003-.012l-.01-.01z"/>
                            <path fill="currentColor"
                                  d="M8.293 12.707a1 1 0 0 1 0-1.414l5.657-5.657a1 1 0 1 1 1.414 1.414L10.414 12l4.95 4.95a1 1 0 0 1-1.414 1.414z"/>
                        </g>
                    </svg>
                </button>
                <span id="pageInfo"><span id="currentPage"
                                          style="padding: 4px 10px;border: 1px solid black;border-radius: 4px;font-weight: bold;">1</span> of <span
                        id="totalPages">1</span></span>
                <button id="nextPageBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24">
                        <g fill="none" fill-rule="evenodd">
                            <path d="M24 0v24H0V0zM12.593 23.258l-.011.002l-.071.035l-.02.004l-.014-.004l-.071-.035q-.016-.005-.024.005l-.004.01l-.017.428l.005.02l.01.013l.104.074l.015.004l.012-.004l.104-.074l.012-.016l.004-.017l-.017-.427q-.004-.016-.017-.018m.265-.113l-.013.002l-.185.093l-.01.01l-.003.011l.018.43l.005.012l.008.007l.201.093q.019.005.029-.008l.004-.014l-.034-.614q-.005-.019-.02-.022m-.715.002a.02.02 0 0 0-.027.006l-.006.014l-.034.614q.001.018.017.024l.015-.002l.201-.093l.01-.008l.004-.011l.017-.43l-.003-.012l-.01-.01z"/>
                            <path fill="currentColor"
                                  d="M15.707 11.293a1 1 0 0 1 0 1.414l-5.657 5.657a1 1 0 1 1-1.414-1.414l4.95-4.95l-4.95-4.95a1 1 0 0 1 1.414-1.414z"/>
                        </g>
                    </svg>
                </button>
            </div>
        </div>
        <div id="fileInfo"></div>
        <div id="loading">Loading...</div>
        <div id="output"></div>
        <div id="errorMsg"></div>
    </div>
    <input type="hidden" id="chatSessionId" value="{{ chat_session }}">
{% endblock %}

{% block js %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mammoth/1.4.2/mammoth.browser.min.js"></script>
    <script src="{% static 'js/document.js' %}"></script>
{% endblock %}

templates/core/sub_base.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="container" style="height: 86vh">
        <div class="row" style="height: 100%;">
            <div class="col col-12 col-xs-12 col-sm-6 col-md-7 col-lg-7 col-xl-8"
                 style="height: 100%;padding: 5px 20px;display: flex;justify-content: center;align-items: center;flex-direction: column">
                <div style="background: rgba(138,137,137,0.06);width: 100%;height: 100%;padding-bottom: 10px;">
                    {% block sub_content %}{% endblock %}
                </div>
            </div>
            <div class="col col-12 col-xs-12 col-sm-6 col-md-5 col-lg-5 col-xl-4" style="padding: 5px 0">
                <div class="msg-header"
                     style="display: flex;flex-direction: row;justify-content: space-between;align-items: center;padding: 5px 10px;">
                    <h4 style="color: white;">Socrate</h4>
                    <svg id="activate_voice_chat" xmlns="http://www.w3.org/2000/svg" color="white" width="40px"
                         height="40px" viewBox="0 0 48 48">
                        <g fill="none" stroke="currentColor" stroke-width="4">
                            <path d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4S4 12.954 4 24s8.954 20 20 20Z"/>
                            <path stroke-linecap="round" d="M30 18v12m6-8v4m-18-8v12m-6-8v4m12-12v20"/>
                        </g>
                    </svg>
                </div>
                <div class="chat-page">
                    <input type="hidden" id="chatSessionId" value="{{ chat_session.id }}">
                    <div class="msg-inbox">
                        <div class="chat-messages">
                            {% for message in chat_messages %}
                                {% if message.message_type == 'text' %}
                                    {% if message.sender == request.user %}
                                        <div class="outgoing-chats">
                                            <div class="outgoing-msg">
                                                <div class="outgoing-chats-msg">
                                                    <p>{{ message.content }}</p>
                                                    <span class="time">{{ message.timestamp|date:"h:i A" }} | {{ message.timestamp|date:"M d" }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class="received-chats">
                                            <div class="received-msg">
                                                <div class="received-msg-inbox">
                                                    <p>{{ message.content }}</p>
                                                    <span class="time">{{ message.timestamp|date:"h:i A" }} | {{ message.timestamp|date:"M d" }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% elif message.message_type == 'voice' %}
                                    {% if message.sender == request.user %}
                                        <div class="outgoing-chats">
                                            <div class="outgoing-msg">
                                                <div class="outgoing-chats-msg">
                                                    {% if message.voice_file %}
                                                        <audio controls>
                                                            <source src="{{ message.voice_file.url }}" type="audio/mp3">
                                                            Your browser does not support the audio element.
                                                        </audio>
                                                    {% else %}
                                                        <p>No audio file available.</p>
                                                    {% endif %}
                                                    <span class="time">{{ message.timestamp|date:"h:i A" }} | {{ message.timestamp|date:"M d" }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    {% else %}
                                        <div class="received-chats">
                                            <div class="received-msg">
                                                <div class="received-msg-inbox">
                                                    {% if message.voice_file %}
                                                        <audio controls>
                                                            <source src="{{ message.voice_file.url }}" type="audio/mp3">
                                                            Your browser does not support the audio element.
                                                        </audio>
                                                    {% else %}
                                                        <p>No audio file available.</p>
                                                    {% endif %}
                                                    <span class="time">{{ message.timestamp|date:"h:i A" }} | {{ message.timestamp|date:"M d" }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="msg-bottom">
                            <div class="input-group">
                                <input id="message-input" name="message" type="text" placeholder="Write message..."/>
                                <div class="input-group-append">
                        <span class="input-group-text send-icon">
                            <button type="submit" id="send-button">
                                <svg xmlns="http://www.w3.org/2000/svg" class="bi bi-send" viewBox="0 0 16 16"
                                     height="25" width="25">
                                    <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576zm6.787-8.201L1.591 6.602l4.339 2.76z"/>
                                </svg>
                            </button>
                        </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/core/video.html
{% extends 'core/sub_base.html' %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/video.css' %}">
{% endblock %}

{% block sub_content %}
    <div style="display: flex;flex-direction: column;align-items: center;justify-content: center;width: 100%;height: 100%">
        <div class="video-container">
            <video id="myVideo" width="100%">
                <source src="{% url 'core:serve_media' path=material.file.name %}" type="video/mp4">
                Your browser does not support the video element.
            </video>
            <button class="center-play-pause" id="centerPlayPauseBtn">
                <svg xmlns="http://www.w3.org/2000/svg" width="50px" height="50px" viewBox="0 0 24 24">
                    <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.5"
                          d="M3 12v6.967c0 2.31 2.534 3.769 4.597 2.648l3.203-1.742M3 8V5.033c0-2.31 2.534-3.769 4.597-2.648l12.812 6.968a2.998 2.998 0 0 1 0 5.294l-6.406 3.484"></path>
                </svg>
            </button>
            <div class="controls">
                <button class="control_buttons" id="backwardBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30px" height="30px" viewBox="0 0 24 24">
                        <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                              stroke-width="1.5" d="M4.5 12l5-5m-5 5l5 5m-5-5h6.5m3.5 0c1.667 0 5 1 5 5"/>
                    </svg>
                </button>
                <button class="control_buttons" id="playPauseBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30px" height="30px" viewBox="0 0 24 24">
                        <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.5"
                              d="M3 12v6.967c0 2.31 2.534 3.769 4.597 2.648l3.203-1.742M3 8V5.033c0-2.31 2.534-3.769 4.597-2.648l12.812 6.968a2.998 2.998 0 0 1 0 5.294l-6.406 3.484"/>
                    </svg>
                </button>
                <button class="control_buttons" id="forwardBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30px" height="30px" viewBox="0 0 24 24">
                        <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                              stroke-width="1.5" d="m19.5 12l-5-5m5 5l-5 5m5-5H13m-3.5 0c-1.667 0-5 1-5 5"/>
                    </svg>
                </button>
                <input type="range" id="seekBar" max="100" min="0" value="0" class="custom-range">
                <button class="control_buttons" id="muteBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 24 24">
                        <path fill="currentColor"
                              d="M12 3.75v16.5a.75.75 0 0 1-1.255.555L5.46 16H2.75A1.75 1.75 0 0 1 1 14.25v-4.5C1 8.784 1.784 8 2.75 8h2.71l5.285-4.805A.75.75 0 0 1 12 3.75M6.255 9.305a.75.75 0 0 1-.505.195h-3a.25.25 0 0 0-.25.25v4.5c0 .138.112.25.25.25h3c.187 0 .367.069.505.195l4.245 3.86V5.445ZM16.28 8.22a.75.75 0 1 0-1.06 1.06L17.94 12l-2.72 2.72a.75.75 0 1 0 1.06 1.06L19 13.06l2.72 2.72a.75.75 0 1 0 1.06-1.06L20.06 12l2.72-2.72a.75.75 0 0 0-1.06-1.06L19 10.94z"/>
                    </svg>
                </button>
                <button class="control_buttons" id="volumeBtn">
                    <svg xmlns="http://www.w3.org/2000/svg" width="30px" height="30px" viewBox="0 0 48 48">
                        <g fill="none" stroke="currentColor" stroke-width="4">
                            <path d="M24 44c11.046 0 20-8.954 20-20S35.046 4 24 4S4 12.954 4 24s8.954 20 20 20Z"/>
                            <path stroke-linecap="round" d="M30 18v12m6-8v4m-18-8v12m-6-8v4m12-12v20"/>
                        </g>
                    </svg>
                </button>
                <div class="volume-slider">
                    <input type="range" id="volumeBar" value="1" min="0" max="1" step="0.1" class="custom-range">
                </div>
                <span style="font-weight: bold;color: white;font-size: 15px;" id="currentTime">0:00 </span> <span
                    style="font-weight: bold;font-size: 16px;color: white;">/</span> <span
                    style="font-size: 15px;font-weight: bold;color: white;" id="duration"> 0:00</span>
            </div>
        </div>
    </div>
    <input type="hidden" id="chatSessionId" value="{{ chat_session }}">
{% endblock %}

{% block js %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script src="{% static 'js/video.js' %}"></script>
{% endblock %}