Socrate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path, reverse_lazy
from accounts import views
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetConfirmView, CustomPasswordResetView

app_name = 'accounts'

urlpatterns = [
    # Registration and Activation
    path('register/', views.register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),

    # Login and Logout
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_user, name='logout'),

    # Password Reset URLs
    path('reset_password/',
         CustomPasswordResetView.as_view(
             template_name='account/password_reset_form.html',
             email_template_name='account/password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done')
         ),
         name='password_reset'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    # Password Change URLs
    path('password_change/',
         auth_views.PasswordChangeView.as_view(
             template_name='account/password_change_form.html',
             success_url=reverse_lazy('accounts:password_change_done')
         ),
         name='password_change_view'),

    path('password_change_done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='account/password_change_done.html'
         ),
         name='password_change_done'),
]

core/urls.py
# core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('upload_material/', views.upload_material, name='upload_material'),
    path('document/<int:pk>/', views.document_detail, name='document_detail'),
    path('video/<int:pk>/', views.video_detail, name='video_detail'),
    path('audio/<int:pk>/', views.audio_detail, name='audio_detail'),
    path('media/<path:path>/', views.serve_media, name='serve_media'),
    path('delete_material/<int:pk>/', views.delete_material, name='delete_material'),
    path('upload_voice_message/', views.upload_voice_message, name='upload_voice_message'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Socrate{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link type="text/css" href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
    <link type="text/css"
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
<header>
    <nav style="width: 100%;padding: 10px 20px;display: flex;flex-direction: row;justify-content: space-between;align-items: center;box-shadow: 0 2px 2px rgba(0,0,0,0.2);margin-bottom: 10px">
            <a href="{% url 'core:home' %}" title="Socrate Homepage">
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
                     y="0px" height="35px"
                     viewBox="0 0 1785.2 370.9" style="enable-background:new 0 0 1785.2 370.9;" xml:space="preserve">
                <g>
                    <g>
                        <path d="M375.5,49.8c-29.2-29.2-68-45.3-109.3-45.3h-71c-25.7,0-50.7,5.1-74.3,15c-22.7,9.6-43.1,23.4-60.6,40.9
                            C42.8,77.9,29,98.3,19.4,121.1c-10,23.6-15,48.5-15,74.3v171h209c28,0,55.1-5.5,80.7-16.3c24.7-10.4,46.9-25.4,65.9-44.4
                            c19-19,34-41.2,44.4-65.9c10.8-25.6,16.3-52.7,16.3-80.7C420.7,117.8,404.7,79,375.5,49.8z M382.6,159
                            c0,93.5-75.8,169.2-169.2,169.2H42.5V195.4c0-84.3,68.4-152.7,152.7-152.7h71C330.5,42.7,382.6,94.8,382.6,159L382.6,159z"/>
                        <g>
                            <g>
                                <path d="M300.5,165.3h-67.9c-0.7,0-1.2-0.5-1.2-1.2v-50.2c0-0.7,0.5-1.2,1.2-1.2h75.9c0.7,0,1.2,0.5,1.2,1.2V156
                                    C309.8,161.1,305.6,165.3,300.5,165.3z"/>
                                <path d="M124.6,165.3h67.9c0.7,0,1.2-0.5,1.2-1.2v-50.2c0-0.7-0.5-1.2-1.2-1.2h-75.9c-0.7,0-1.2,0.5-1.2,1.2V156
                                    C115.3,161.1,119.5,165.3,124.6,165.3z"/>
                            </g>
                            <path d="M265.8,256.5H159.3c-1.4,0-2.5-1.1-2.5-2.5v-10.3c0-0.1,0-0.1,0.1-0.1h111.3c0.1,0,0.1,0,0.1,0.1V254
                                C268.3,255.4,267.2,256.5,265.8,256.5z"/>
                        </g>
                    </g>
                    <g>
                        <path d="M646.3,237.3c0,15.7-4,29.8-12.1,42.3c-8.1,12.5-19.9,22.3-35.5,29.4c-15.6,7.1-34.1,10.6-55.4,10.6
                            c-25.6,0-46.7-4.8-63.4-14.5c-11.8-7-21.4-16.3-28.8-27.9c-7.4-11.6-11.1-22.9-11.1-33.9c0-6.4,2.2-11.8,6.6-16.4
                            c4.4-4.5,10.1-6.8,16.9-6.8c5.5,0,10.2,1.8,14.1,5.3c3.8,3.5,7.1,8.8,9.8,15.8c3.3,8.3,6.9,15.2,10.7,20.7
                            c3.8,5.5,9.2,10.1,16.2,13.7c7,3.6,16.1,5.4,27.4,5.4c15.6,0,28.2-3.6,38-10.9c9.7-7.3,14.6-16.3,14.6-27.2c0-8.6-2.6-15.6-7.9-21
                            c-5.3-5.4-12-9.5-20.4-12.3c-8.3-2.8-19.4-5.8-33.4-9c-18.6-4.4-34.3-9.5-46.8-15.3c-12.6-5.8-22.5-13.8-29.9-23.9
                            c-7.4-10.1-11.1-22.6-11.1-37.6c0-14.3,3.9-27,11.7-38.1c7.8-11.1,19.1-19.6,33.8-25.6c14.8-6,32.1-8.9,52-8.9
                            c15.9,0,29.7,2,41.3,5.9c11.6,4,21.3,9.2,28.9,15.8c7.7,6.5,13.3,13.4,16.8,20.6c3.5,7.2,5.3,14.2,5.3,21.1
                            c0,6.3-2.2,11.9-6.6,16.9c-4.4,5-9.9,7.5-16.6,7.5c-6,0-10.6-1.5-13.7-4.5c-3.1-3-6.5-7.9-10.2-14.8c-4.7-9.8-10.4-17.4-17-22.9
                            c-6.6-5.5-17.2-8.2-31.9-8.2c-13.6,0-24.5,3-32.8,8.9c-8.3,6-12.5,13.1-12.5,21.5c0,5.2,1.4,9.7,4.2,13.5c2.8,3.8,6.7,7,11.7,9.7
                            c5,2.7,10,4.8,15,6.4c5.1,1.5,13.5,3.8,25.1,6.7c14.6,3.4,27.9,7.2,39.7,11.3c11.9,4.1,22,9.1,30.3,15
                            c8.3,5.9,14.8,13.4,19.5,22.4C643.9,213.2,646.3,224.2,646.3,237.3z"/>
                        <path d="M868.4,221.4c0,14.4-2.2,27.7-6.7,39.8c-4.5,12.2-11,22.6-19.5,31.3c-8.5,8.7-18.6,15.4-30.4,20.1
                            c-11.8,4.7-25.1,7-39.8,7c-14.6,0-27.8-2.4-39.5-7.1c-11.7-4.7-21.8-11.5-30.4-20.3c-8.6-8.8-15-19.2-19.5-31.2
                            c-4.4-12-6.6-25.2-6.6-39.7c0-14.6,2.2-28,6.7-40.2c4.5-12.2,10.9-22.5,19.3-31.2c8.4-8.6,18.5-15.3,30.4-19.9
                            c11.9-4.7,25.1-7,39.5-7c14.6,0,27.9,2.4,39.8,7.1c11.9,4.7,22.1,11.4,30.6,20.2c8.5,8.7,15,19.1,19.4,31.2
                            C866.2,193.6,868.4,206.9,868.4,221.4z M819.9,221.4c0-19.7-4.3-35.1-13-46c-8.7-11-20.3-16.5-35-16.5c-9.4,0-17.8,2.5-25,7.3
                            c-7.2,4.9-12.7,12.1-16.6,21.7c-3.9,9.6-5.8,20.7-5.8,33.5c0,12.6,1.9,23.7,5.8,33.1c3.8,9.4,9.3,16.7,16.5,21.7
                            c7.1,5,15.5,7.5,25.2,7.5c14.6,0,26.3-5.5,35-16.6C815.6,256.1,819.9,240.9,819.9,221.4z"/>
                        <path d="M1079.8,259.8c0,6-1.8,12.5-5.4,19.3c-3.6,6.8-9.1,13.4-16.5,19.6c-7.4,6.2-16.7,11.2-27.9,15
                            c-11.2,3.8-23.8,5.7-37.9,5.7c-29.9,0-53.2-8.7-69.9-26.1c-16.8-17.4-25.1-40.7-25.1-70c0-19.8,3.8-37.4,11.5-52.6
                            c7.7-15.2,18.8-27,33.3-35.3s31.9-12.5,52-12.5c12.5,0,24,1.8,34.4,5.5c10.4,3.7,19.3,8.4,26.6,14.2c7.3,5.8,12.8,11.9,16.6,18.5
                            c3.8,6.5,5.8,12.7,5.8,18.3c0,5.8-2.2,10.7-6.5,14.7c-4.3,4-9.5,6-15.7,6c-4,0-7.3-1-10-3.1c-2.7-2.1-5.6-5.4-8.9-10
                            c-5.9-9-12.1-15.7-18.5-20.2c-6.4-4.5-14.6-6.7-24.5-6.7c-14.3,0-25.8,5.6-34.5,16.7c-8.7,11.2-13.1,26.4-13.1,45.8
                            c0,9.1,1.1,17.4,3.4,25c2.2,7.6,5.5,14.1,9.7,19.5c4.2,5.4,9.4,9.4,15.4,12.2c6,2.8,12.6,4.2,19.8,4.2c9.7,0,18-2.2,24.9-6.7
                            c6.9-4.5,13-11.3,18.3-20.5c2.9-5.4,6.1-9.7,9.6-12.7c3.4-3.1,7.6-4.6,12.6-4.6c5.9,0,10.8,2.2,14.7,6.7
                            C1077.9,250,1079.8,254.7,1079.8,259.8z"/>
                        <path d="M1169.9,249.9v40.4c0,9.8-2.3,17.1-6.9,22c-4.6,4.9-10.4,7.3-17.5,7.3c-7,0-12.7-2.5-17.2-7.4c-4.5-5-6.7-12.3-6.7-22
                            V155.7c0-21.7,7.8-32.6,23.5-32.6c8,0,13.8,2.5,17.3,7.6c3.5,5.1,5.5,12.6,5.8,22.5c5.8-9.9,11.7-17.4,17.8-22.5
                            c6.1-5.1,14.2-7.6,24.3-7.6c10.1,0,20,2.5,29.6,7.6c9.6,5.1,14.3,11.8,14.3,20.2c0,5.9-2,10.8-6.1,14.6c-4.1,3.8-8.5,5.8-13.2,5.8
                            c-1.8,0-6-1.1-12.8-3.3c-6.8-2.2-12.8-3.3-18-3.3c-7.1,0-12.9,1.9-17.3,5.6c-4.5,3.7-8,9.2-10.4,16.6c-2.5,7.3-4.2,16-5.1,26.1
                            C1170.4,223.1,1169.9,235.4,1169.9,249.9z"/>
                        <path d="M1393.9,292.4c-11.7,9.1-23,15.9-33.9,20.4c-10.9,4.5-23.2,6.8-36.7,6.8c-12.4,0-23.3-2.5-32.7-7.3
                            c-9.4-4.9-16.6-11.5-21.7-19.9c-5.1-8.4-7.6-17.5-7.6-27.3c0-13.2,4.2-24.5,12.6-33.8c8.4-9.3,19.9-15.6,34.5-18.8
                            c3.1-0.7,10.7-2.3,22.8-4.8c12.2-2.5,22.6-4.7,31.2-6.8c8.7-2.1,18.1-4.6,28.2-7.5c-0.6-12.7-3.2-22.1-7.7-28.1
                            c-4.5-6-14-8.9-28.2-8.9c-12.3,0-21.5,1.7-27.7,5.1c-6.2,3.4-11.5,8.6-15.9,15.4c-4.4,6.8-7.6,11.4-9.4,13.5
                            c-1.8,2.2-5.8,3.3-11.8,3.3c-5.4,0-10.1-1.7-14.1-5.2c-4-3.5-5.9-7.9-5.9-13.4c0-8.5,3-16.8,9-24.8c6-8,15.4-14.6,28.1-19.8
                            c12.7-5.2,28.6-7.8,47.6-7.8c21.2,0,37.9,2.5,50.1,7.5c12.2,5,20.7,13,25.8,23.8c5,10.9,7.5,25.3,7.5,43.2c0,11.3,0,21-0.1,28.9
                            c-0.1,7.9-0.1,16.7-0.3,26.4c0,9.1,1.5,18.6,4.5,28.4c3,9.9,4.5,16.2,4.5,19c0,5-2.3,9.5-7,13.5c-4.7,4.1-9.9,6.1-15.8,6.1
                            c-5,0-9.9-2.3-14.7-7C1404.4,308,1399.3,301.2,1393.9,292.4z M1390.7,222.5c-7.1,2.6-17.4,5.3-30.9,8.2c-13.5,2.9-22.9,5-28.1,6.4
                            c-5.2,1.4-10.2,4-14.9,8c-4.7,4-7.1,9.5-7.1,16.6c0,7.3,2.8,13.5,8.3,18.7c5.5,5.1,12.8,7.7,21.8,7.7c9.6,0,18.4-2.1,26.5-6.3
                            c8.1-4.2,14-9.6,17.8-16.2c4.4-7.3,6.5-19.4,6.5-36.1V222.5z"/>
                        <path d="M1480.8,127.4h5.3v-29c0-7.8,0.2-13.9,0.6-18.3c0.4-4.4,1.6-8.2,3.5-11.4c1.9-3.3,4.6-6,8.1-8.1c3.5-2.1,7.5-3.1,11.9-3.1
                            c6.1,0,11.7,2.3,16.6,6.9c3.3,3.1,5.4,6.8,6.3,11.2s1.3,10.7,1.3,18.9v32.9h17.7c6.8,0,12.1,1.6,15.7,4.9
                            c3.6,3.2,5.4,7.4,5.4,12.5c0,6.5-2.6,11-7.7,13.6c-5.1,2.6-12.5,3.9-22,3.9h-9v88.9c0,7.6,0.3,13.4,0.8,17.4
                            c0.5,4.1,1.9,7.4,4.2,9.9c2.3,2.5,6,3.8,11.2,3.8c2.8,0,6.7-0.5,11.5-1.5c4.8-1,8.6-1.5,11.3-1.5c3.9,0,7.4,1.6,10.5,4.7
                            c3.1,3.1,4.7,7,4.7,11.6c0,7.8-4.2,13.8-12.7,17.9c-8.5,4.1-20.7,6.2-36.6,6.2c-15.1,0-26.6-2.5-34.3-7.6
                            c-7.8-5.1-12.9-12.1-15.3-21.1c-2.4-9-3.6-20.9-3.6-35.9v-92.8h-6.4c-7,0-12.3-1.7-15.9-5c-3.7-3.3-5.5-7.5-5.5-12.6
                            c0-5.1,1.9-9.2,5.8-12.5C1467.9,129,1473.5,127.4,1480.8,127.4z"/>
                        <path d="M1741.4,233.3h-94.5c0.1,11,2.3,20.7,6.6,29c4.3,8.4,10,14.7,17.2,18.9c7.1,4.2,15,6.4,23.6,6.4c5.8,0,11.1-0.7,15.8-2
                            c4.8-1.4,9.4-3.5,13.9-6.4c4.5-2.9,8.6-6,12.4-9.3c3.8-3.3,8.7-7.8,14.7-13.5c2.5-2.1,6-3.2,10.6-3.2c5,0,9,1.4,12,4.1
                            c3.1,2.7,4.6,6.6,4.6,11.5c0,4.4-1.7,9.5-5.1,15.3c-3.4,5.8-8.6,11.4-15.5,16.8c-6.9,5.4-15.6,9.8-26,13.4
                            c-10.4,3.5-22.5,5.3-36,5.3c-31,0-55.2-8.9-72.4-26.6c-17.2-17.7-25.8-41.7-25.8-72.1c0-14.3,2.1-27.5,6.4-39.7
                            c4.2-12.2,10.4-22.7,18.6-31.4c8.1-8.7,18.2-15.4,30.1-20.1c11.9-4.7,25.1-7,39.7-7c18.9,0,35.1,4,48.6,11.9
                            c13.5,8,23.6,18.3,30.4,30.9c6.7,12.6,10.1,25.5,10.1,38.6c0,12.2-3.5,20-10.4,23.6C1763.8,231.5,1754,233.3,1741.4,233.3z
                             M1646.8,205.8h87.6c-1.2-16.5-5.6-28.9-13.4-37.1c-7.7-8.2-17.9-12.3-30.5-12.3c-12,0-21.9,4.2-29.7,12.5
                            C1653.2,177.2,1648.5,189.5,1646.8,205.8z"/>
                    </g>
                </g>
                <g>
                </g>
                <g>
                </g>
                <g>
                </g>
                <g>
                </g>
                <g>
                </g>
                </svg>
            </a>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">
                <svg xmlns="http://www.w3.org/2000/svg" color="black" width="50px" height="50px" viewBox="0 0 24 24">
                    <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.5">
                        <path d="M8 16c0 2.828 0 4.243.879 5.121c.641.642 1.568.815 3.121.862M8 8c0-2.828 0-4.243.879-5.121C9.757 2 11.172 2 14 2h1c2.828 0 4.243 0 5.121.879C21 3.757 21 5.172 21 8v8c0 2.828 0 4.243-.879 5.121c-.768.769-1.946.865-4.121.877M3 9.5v5c0 2.357 0 3.535.732 4.268c.732.732 1.911.732 4.268.732M3.732 5.232C4.464 4.5 5.643 4.5 8 4.5"></path>
                        <path stroke-linejoin="round" d="M6 12h9m0 0l-2.5 2.5M15 12l-2.5-2.5"></path>
                    </g>
                </svg>
            </a>
        {% else %}
            <a href="{% url 'accounts:login' %}">
                <svg xmlns="http://www.w3.org/2000/svg" color="black" width="50px" height="50px" viewBox="0 0 24 24">
                    <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.5">
                        <path stroke-linejoin="round" d="M15 12H6m0 0l2 2m-2-2l2-2"></path>
                        <path d="M12 21.983c-1.553-.047-2.48-.22-3.121-.862c-.769-.768-.865-1.946-.877-4.121M16 21.998c2.175-.012 3.353-.108 4.121-.877C21 20.243 21 18.828 21 16V8c0-2.828 0-4.243-.879-5.121C19.243 2 17.828 2 15 2h-1c-2.828 0-4.243 0-5.121.879c-.769.768-.865 1.946-.877 4.121M3 9.5v5c0 2.357 0 3.535.732 4.268c.732.732 1.911.732 4.268.732M3.732 5.232C4.464 4.5 5.643 4.5 8 4.5"></path>
                    </g>
                </svg>
            </a>
        {% endif %}
    </nav>
</header>
{% block content %}{% endblock %}
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>